// Build dsh-xiaoba-brand: regenerate lib/client.js from src/ + assets/.
//
// The browser half is generated rather than hand-written because two of its three
// pieces are large machine-produced blobs that must stay byte-exact:
//
//   assets/xiaoba.svg                  the uploaded mark, inlined verbatim into
//                                      the sidebar and hero slot components
//   assets/wordmark-linhaoming.path.txt  glyph outlines for the replacement name
//   assets/harness-badge.json          the seven HARNESS glyph paths lifted from
//                                      the stock brand, carried over unchanged
//
// Everything else (config surface, slot wiring, hero copy patch) is ordinary
// source in src/client.template.js, concatenated after the generated prologue.
//
// Zero build dependencies on purpose: this plugin ships as a plain profile
// bundle and must not drag a toolchain into the host. Run: node tools/build.mjs
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const read = (p) => readFileSync(join(root, p), "utf8");
const pkg = JSON.parse(read("package.json"));
const id = pkg.name;

// --- generated prologue -----------------------------------------------------

const svg = read("assets/xiaoba.svg");
const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "");
// The artwork is embedded in a JS string literal, so the delimiter characters
// must not occur in it. They never do for a VTracer trace, but assert rather
// than emit a file that fails to parse.
for (const bad of ["\u0060", "${", "\\"]) {
  if (inner.includes(bad)) throw new Error(`assets/xiaoba.svg contains a JS-unsafe sequence: ${bad}`);
}
const linhao = read("assets/wordmark-linhaoming.path.txt").trim();
const badge = JSON.parse(read("assets/harness-badge.json"))
  .filter(([, fill]) => fill !== "white")
  .map(([d]) => d);
if (badge.length !== 7) throw new Error(`expected 7 HARNESS glyphs, found ${badge.length}`);

const json = (s) => JSON.stringify(s);

let out = "";
out += `// dsh-xiaoba-brand client half — GENERATED by tools/build.mjs, do not edit.\n`;
out += `// Source of truth: src/client.template.js plus the files in assets/.\n\n`;
out += `var XIAOBA_VIEWBOX = "0 0 631 631";\n`;
out += `var XIAOBA_INNER = ${json(inner)};\n\n`;
out += `var WORDMARK_VIEWBOX = "26 0 156 24";\n`;
out += `var LINHAO_TRANSFORM = ${json("translate(22.9302 -0.9445) scale(0.163275)")};\n`;
out += `var LINHAO_PATH = ${json(linhao)};\n\n`;
out += `var HARNESS_GLYPHS = [\n`;
for (const d of badge) out += `  ${json(d)},\n`;
out += `];\n\n`;

out += read("src/client.template.js");

// The browser half must arrive as the factory-form CJS the client module system
// registers: the bundle is executed as a classic script, and executing it may
// only REGISTER a factory (window.__ModuleLoader__.load({id, factory})). Emitting
// the template body bare made the browser throw "require is not defined" at the
// first `var React = require("react")` line, which fails the whole web boot.
const wrapped = `window.__ModuleLoader__.load({\n\tid: ${json(id)},\n\tfactory: (require) => {\n\t\tvar module = { exports: {} };\n\t\tvar exports = module.exports;\n${out}\n\t\treturn module.exports;\n\t}\n});\n`;

mkdirSync(join(root, "lib"), { recursive: true });
writeFileSync(join(root, "lib", "client.js"), wrapped);
console.log(`lib/client.js written (${wrapped.length} bytes)`);

// The Node half has no generation step: it is plain ESM, copied verbatim so the
// shipped lib/ matches src/ without a build tool in the loop.
copyFileSync(join(root, "src", "index.js"), join(root, "lib", "index.js"));
console.log("lib/index.js written");

